config/routes.rb
Rails.application.routes.draw do
  #get 'comments/new'

  #get 'comments/create'

  #get 'comments/destroy'

  get 'comments', to: "comments#index", as: "comments"

  devise_for :users

  root 'articles#index'
  resources :articles do
    member do
      put 'like',    to: "articles#upvote"
      put 'dislike', to: "articles#downvote"
    end
    collection do
      # latest articles 'New'
      get 'latest',  to: "articles#latest"
    end
    resources :comments, shallow: true do
      member do
        put 'like',    to: "comments#upvote"
        put 'dislike', to: "comments#downvote"
      end
    end
  end

  resources  :users do
    get 'comments', on: :member
    get 'articles', on: :member
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validate  :url_body
  acts_as_votable
  def score
      self.get_upvotes.size - self.get_downvotes.size
  end
  private
    # one of url or body should be entered
     def url_body
       if url.blank? and body.blank?
         errors.add(:url, " One of url or body should be entered.")
       end
     end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  acts_as_votable
  def score
      self.get_upvotes.size - self.get_downvotes.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
  validates :name, presence: true, length: { maximum: 50 }

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password, :password_confirmation, :email])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only: [ :show, :edit, :destroy , :update, :upvote, :downvote]
  before_action :authenticate_user!, except: [ :index, :show , :latest]

  def index
    #@articles = Article.order("created_at DESC")
    #@articles = Article.order("created_at DESC")
    #<%= post.weighted_average.round(2) %>
    @articles = Article.order(:cached_weighted_total => :desc)
    #@articles = Article.order(:score)
  end
  # called by clicking New on _header
  def latest
    @articles = Article.order("created_at DESC")
    #<%= post.weighted_average.round(2) %>
  end
  def new
    @article = current_user.articles.new
  end
  def create
    @article = current_user.articles.build(article_params)
    if @article.url.blank? and @article.body.blank?
      flash[:error] = "One of URL or text must be entered"
      render 'new'
      return
    end
    if @article.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end
  def show
  end
  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    @article.destroy
    redirect_to articles_path
  end
  def upvote
    if current_user.liked? @article
      @article.unliked_by current_user
    else
      @article.upvote_by current_user
    end
    #redirect_to articles_path
    redirect_to :back
  end
  def downvote
    if current_user.disliked? @article
      @article.undisliked_by current_user
    else
      @article.downvote_by current_user
    end
    redirect_to :back
  end

  private
    def article_params
      params.require(:article).permit(:title, :url, :body, :tldr)
    end
    def get_article
      @article = Article.find(params[:id])
      #if @article.url.blank?
        #@article_url = article_path(@article)
      #end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  # all recent comments, on Comment link
  def index
    @comments = Comment.order("created_at DESC")
  end
  def create
    @article = Article.find(params[:article_id])
    # I need to allow user_id here too since i am updating it as a hidden field.
    # Or else I could have added it here ??
    @comment = @article.comments.create(params[:comment].permit(:name, :body, :user_id))
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
      format.js
    end

    #redirect_to article_path(@article)
  end
  def destroy
    #puts "PARAMS"
    #puts params.inspect
    #@article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    @article = @comment.article
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
  def upvote
    @comment = Comment.find(params[:id])
    if current_user.liked? @comment
      @comment.unliked_by current_user
    else
      @comment.upvote_by current_user
    end

    @article = @comment.article
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
      format.js
    end
  end
  def downvote
    @comment = Comment.find(params[:id])
    #@comment.downvote_by current_user
    if current_user.disliked? @comment
      @comment.undisliked_by current_user
    else
      @comment.downvote_by current_user
    end
    @article = @comment.article
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
      format.js
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def comments
    @comments = current_user.comments.order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true,  hard_wrap: true)
		options = {
			:fenced_code_blocks => true,
			:no_intra_emphasis => true,
			:autolink => true,
			:strikethrough => true,
			:lax_html_blocks => true,
			:superscript => true
		}
		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.haml
.li
  .first_row
    - if article.url.blank?
      - article.url = article_path(article)
    = link_to article.title, article.url 
    %br/
  .second_row
    #{article.score} points
    by #{link_to article.user.name, article.user}
    #{time_ago_in_words(article.created_at)} ago
    |
    Score: #{article.cached_weighted_total.round(2)}
    |
    = link_to "#{article.comments.size} comments", article

    - if current_user &&  article.user != current_user
      |
      - if current_user.liked? article
        = link_to "Unlike", like_article_path(article), method: :put 
      - else
        = link_to "Like", like_article_path(article), method: :put 
      |
      - if current_user.disliked? article
        = link_to "Undislike", dislike_article_path(article), method: :put
      - else
        = link_to "Dislike", dislike_article_path(article), method: :put
  

app/views/articles/edit.html.haml
%h1 Edit Article
.row
  .col-md-6.col-md-offset-3
    = simple_form_for( @article) do |f|
      = f.error_notification
      
      = f.input :title
      = f.input :url
      Or
      = f.input :body
      = f.input :tldr
      = f.button :submit

app/views/articles/index.html.haml
.container
  %ol.article
    = render @articles

app/views/articles/latest.html.haml
.container
  %ol.article
    = render @articles

app/views/articles/new.html.haml
%h1 New Article
.row
  .col-md-6.col-md-offset-3
    = simple_form_for( @article) do |f|
      = f.error_notification
      
      = f.input :title, placeholder: 'Enter title'
      = f.input :url, placeholder: 'Enter link'
      Or
      = f.input :body
      = f.input :tldr
      = f.button :submit

app/views/articles/show.html.haml
#post_content
  .title= link_to @article.title, @article.url

  %p.date_and_author
    #{@article.score} points
    by #{link_to @article.user.name, @article.user}
    #{time_ago_in_words(@article.created_at)} ago
    |
    Score: #{@article.cached_weighted_total.round(2)}
    |
    = link_to "#{@article.comments.size} comments", @article

    - if current_user
      - if @article.user == current_user
        | 
        = link_to 'Edit', edit_article_path(@article) 
        |
        = link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }
      - else
        |
        - if current_user.liked? @article
          = link_to "Unlike", like_article_path(@article), method: :put 
        - else
          = link_to "Like", like_article_path(@article), method: :put 
        |
        - if current_user.disliked? @article
          = link_to "Undislike", dislike_article_path(@article), method: :put
        - else
          = link_to "Dislike", dislike_article_path(@article), method: :put


  - if !@article.body.blank?
    .well
      = markdown(@article.body)

  .container
    .comment_table
      = render @article.comments
    - if user_signed_in?
      %h1= "Add a comment"
      = render "comments/form"
    - else
      %strong If you were logged in, you could add a comment

app/views/comments/_comment.html.haml
#post_content
  %blockquote
    .date_and_author
      = link_to "#{comment.user.name},", user_path(comment.user)
      = "#{time_ago_in_words(comment.created_at)} ago"
      = "#{comment.score} points."
      <!-- don't show a link to the post if the comments are shown on the same post page -->
      <!-- Some articles got deleted but their comments still linger on - this causes a crash -->
      <!-- Next line crashes if user not logged in                                            -->
      <!-- if current_page?(comments_path) or current_page?(comments_user_path(current_user)) -->
      - if comment.article.nil?
        = " (article deleted) "
      - else
        in
        = link_to comment.article.title, comment.article

      - if comment.user == current_user
        |
        = link_to "Delete", comment_path(comment), method: :delete, remote: true, class: 'delete_comment'
      - else
        |
        - if current_user
          - if current_user.liked? comment
            = link_to "Unlike", like_comment_path(comment), method: :put
          - else
            = link_to "Like", like_comment_path(comment), method: :put
          |
          - if current_user.disliked? comment
            = link_to "Undislike", dislike_comment_path(comment), method: :put
          - else
            = link_to "Dislike", dislike_comment_path(comment), method: :put
      
    .comment-body= markdown(comment.body)

app/views/comments/_form.html.haml
= simple_form_for([@article, @article.comments.build(user_id: current_user.id)], remote: true) do |f|
    = f.hidden_field :user_id, value:  current_user.id
    = f.input :body , label: false, placeholder: "Say something"
    = f.button :submit

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$(".comment_table").html("<%= escape_javascript(render @article.comments) %>") 
/* the next line is optional, it hides then fades in the last line */
/* http://stackoverflow.com/questions/978708/jquery-append-fadein/978731#978731  */
$(".comment_table").children(':last').hide().fadeIn(2000);

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
/* this works but if you delete in teh center then gaps are left in between */
$('.delete_comment').bind('ajax:success', function() {
     $(this).closest('blockquote').fadeOut(2000);
});
/* this immediately redraws so the fadeout is not noticed */
$(".comment_table").html("<%= escape_javascript(render @article.comments) %>") 

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%= render @comments %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Hacker News Clone written in Ruby on Rails 4.2.6.
  %nav
    %ul
      %li= link_to "About", '#'
      %li= link_to "Contact", '#'
      %li
        %a{ href: "https://news.ycombinator.com/news", title: "HN" }
          HN

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
      <div class="navbar-header">
        <%= link_to "Hacker News", root_path, class: "navbar-brand" %> 
      </div>
      <ul class="nav navbar-nav">
           <li><%= link_to "New", latest_articles_path %></li> 
           <% if user_signed_in? %>
             <li><%= link_to "Threads", comments_user_path(current_user) %></li> 
           <% end %>
           <li><%= link_to "Comments", comments_path %></li> 
           <li><%= link_to "Submit", new_article_path %></li> 
      </ul>

        <ul class="nav navbar-nav navbar-right"> 
           <% if user_signed_in? %>
               <li><%= link_to current_user.name, current_user  %></li>
 
               <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       Account <b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                       <li><%= link_to "Profile", current_user %></li>
                       <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                       <li class="divider"></li>
                       <li>
                           <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                       </li>
                   </ul>
               </li>
           <% else %>
             <li><%= link_to new_user_session_path do %>
               <span class="glyphicon glyphicon-log-in"></span> Log In
             <% end %>
           </li>

           <% end %>
        </ul> 
      </nav>
   </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do | message_type, message | %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %> 
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/users/comments.html.haml
%h1= "Comments by #{current_user.name}"
= render @comments

app/views/users/show.html.haml
.container
  %h1 Profile of #{@user.name}
  %p= "Articles posted: " + @user.articles.count.to_s
  %p= "Comments posted: " + @user.comments.count.to_s
  %p= "Joined #{@user.created_at}"